if(NOT FTE_ENGINE)
	return()
endif()

set(FTE_ENGINE_COMMON_SOURCES
	${FTE_ENGINE_GL_DIR}/gl_alias.c
	${FTE_ENGINE_GL_DIR}/gl_hlmdl.c
	${FTE_ENGINE_GL_DIR}/gl_heightmap.c
	${FTE_ENGINE_GL_DIR}/gl_model.c
	${FTE_ENGINE_GL_DIR}/glmod_doom.c

	${FTE_ENGINE_CLIENT_DIR}/m_download.c
	${FTE_ENGINE_CLIENT_DIR}/r_d3.c
	${FTE_ENGINE_CLIENT_DIR}/net_master.c

	${FTE_ENGINE_HTTP_DIR}/httpclient.c
	${FTE_ENGINE_HTTP_DIR}/iwebiface.c

	${FTE_ENGINE_COMMON_DIR}/com_bih.c
	${FTE_ENGINE_COMMON_DIR}/com_mesh.c
	${FTE_ENGINE_COMMON_DIR}/common.c
	${FTE_ENGINE_COMMON_DIR}/json.c
	${FTE_ENGINE_COMMON_DIR}/cvar.c
	${FTE_ENGINE_COMMON_DIR}/cmd.c
	${FTE_ENGINE_COMMON_DIR}/crc.c
	${FTE_ENGINE_COMMON_DIR}/net_ssl_gnutls.c
	${FTE_ENGINE_COMMON_DIR}/fs.c
	${FTE_ENGINE_COMMON_DIR}/fs_stdio.c
	${FTE_ENGINE_COMMON_DIR}/fs_pak.c
	${FTE_ENGINE_COMMON_DIR}/fs_zip.c
	${FTE_ENGINE_COMMON_DIR}/fs_dzip.c
	${FTE_ENGINE_COMMON_DIR}/fs_xz.c
	${FTE_ENGINE_COMMON_DIR}/mathlib.c
	${FTE_ENGINE_COMMON_DIR}/huff.c
	${FTE_ENGINE_COMMON_DIR}/md4.c
	${FTE_ENGINE_COMMON_DIR}/md5.c
	${FTE_ENGINE_COMMON_DIR}/sha1.c
	${FTE_ENGINE_COMMON_DIR}/sha2.c
	${FTE_ENGINE_COMMON_DIR}/log.c
	${FTE_ENGINE_COMMON_DIR}/net_chan.c
	${FTE_ENGINE_COMMON_DIR}/net_wins.c
	${FTE_ENGINE_COMMON_DIR}/net_ice.c
	${FTE_ENGINE_COMMON_DIR}/zone.c
	${FTE_ENGINE_COMMON_DIR}/qvm.c
	${FTE_ENGINE_COMMON_DIR}/gl_q2bsp.c
	${FTE_ENGINE_COMMON_DIR}/pmove.c
	${FTE_ENGINE_COMMON_DIR}/pmovetst.c
	${FTE_ENGINE_COMMON_DIR}/translate.c
	${FTE_ENGINE_COMMON_DIR}/plugin.c
	${FTE_ENGINE_COMMON_DIR}/q1bsp.c
	${FTE_ENGINE_COMMON_DIR}/q2pmove.c

	${FTE_ENGINE_SERVER_DIR}/world.c
	${FTE_ENGINE_SERVER_DIR}/sv_phys.c
	${FTE_ENGINE_SERVER_DIR}/sv_move.c
)

set(FTE_ENGINE_SERVER_SOURCES
	${FTE_ENGINE_SERVER_DIR}/pr_cmds.c
	${FTE_ENGINE_SERVER_DIR}/pr_q1qvm.c
	${FTE_ENGINE_SERVER_DIR}/pr_lua.c
	${FTE_ENGINE_SERVER_DIR}/sv_master.c
	${FTE_ENGINE_SERVER_DIR}/sv_init.c
	${FTE_ENGINE_SERVER_DIR}/sv_main.c
	${FTE_ENGINE_SERVER_DIR}/sv_nchan.c
	${FTE_ENGINE_SERVER_DIR}/sv_ents.c
	${FTE_ENGINE_SERVER_DIR}/sv_send.c
	${FTE_ENGINE_SERVER_DIR}/sv_user.c
	${FTE_ENGINE_SERVER_DIR}/sv_sql.c
	${FTE_ENGINE_SERVER_DIR}/sv_mvd.c
	${FTE_ENGINE_SERVER_DIR}/sv_ccmds.c
	${FTE_ENGINE_SERVER_DIR}/sv_cluster.c
	${FTE_ENGINE_SERVER_DIR}/sv_rankin.c
	${FTE_ENGINE_SERVER_DIR}/sv_chat.c
	${FTE_ENGINE_SERVER_DIR}/sv_demo.c
	${FTE_ENGINE_SERVER_DIR}/net_preparse.c
	${FTE_ENGINE_SERVER_DIR}/savegame.c
	${FTE_ENGINE_SERVER_DIR}/svq2_ents.c
	${FTE_ENGINE_SERVER_DIR}/svq2_game.c

	${FTE_ENGINE_HTTP_DIR}/webgen.c
	${FTE_ENGINE_HTTP_DIR}/ftpserver.c
	${FTE_ENGINE_HTTP_DIR}/httpserver.c
)

set(FTE_ENGINE_PROGS_SOURCES
	${FTE_ENGINE_COMMON_DIR}/pr_bgcmd.c

	${FTE_ENGINE_CLIENT_DIR}/pr_skelobj.c

	${FTE_ENGINE_QCLIB_DIR}/comprout.c
	${FTE_ENGINE_QCLIB_DIR}/hash.c
	${FTE_ENGINE_QCLIB_DIR}/qcc_cmdlib.c
	${FTE_ENGINE_QCLIB_DIR}/qccmain.c
	${FTE_ENGINE_QCLIB_DIR}/qcc_pr_comp.c
	${FTE_ENGINE_QCLIB_DIR}/qcc_pr_lex.c
	${FTE_ENGINE_QCLIB_DIR}/qcd_main.c
	${FTE_ENGINE_QCLIB_DIR}/initlib.c
	${FTE_ENGINE_QCLIB_DIR}/pr_edict.c
	${FTE_ENGINE_QCLIB_DIR}/pr_exec.c
	${FTE_ENGINE_QCLIB_DIR}/pr_multi.c
	${FTE_ENGINE_QCLIB_DIR}/pr_x86.c
	${FTE_ENGINE_QCLIB_DIR}/qcdecomp.c
)

set(FTE_ENGINE_SERVER_ONLY_SOURCES
	$<$<BOOL:${WIN32}>:${FTE_ENGINE_SERVER_DIR}/sv_sys_win.c>
	$<$<BOOL:${WIN32}>:${FTE_ENGINE_COMMON_DIR}/sys_win_threads.c>
	$<$<BOOL:${WIN32}>:${FTE_ENGINE_COMMON_DIR}/net_ssl_winsspi.c>
	$<$<BOOL:${UNIX}>:${FTE_ENGINE_SERVER_DIR}/sv_sys_unix.c>
	$<$<BOOL:${UNIX}>:${FTE_ENGINE_COMMON_DIR}/sys_linux_threads.c>
)

set(FTE_ENGINE_CLIENT_SOURCES
	${FTE_ENGINE_CLIENT_DIR}/textedit.c
	${FTE_ENGINE_CLIENT_DIR}/fragstats.c
	${FTE_ENGINE_CLIENT_DIR}/zqtp.c
	${FTE_ENGINE_CLIENT_DIR}/cl_demo.c
	${FTE_ENGINE_CLIENT_DIR}/cl_ents.c
	${FTE_ENGINE_CLIENT_DIR}/clq2_ents.c
	${FTE_ENGINE_CLIENT_DIR}/cl_input.c
	${FTE_ENGINE_CLIENT_DIR}/in_generic.c
	${FTE_ENGINE_CLIENT_DIR}/cl_main.c
	${FTE_ENGINE_CLIENT_DIR}/cl_parse.c
	${FTE_ENGINE_CLIENT_DIR}/cl_pred.c
	${FTE_ENGINE_CLIENT_DIR}/cl_tent.c
	${FTE_ENGINE_CLIENT_DIR}/cl_cam.c
	${FTE_ENGINE_CLIENT_DIR}/cl_screen.c
	${FTE_ENGINE_CLIENT_DIR}/pr_clcmd.c
	${FTE_ENGINE_CLIENT_DIR}/cl_ignore.c
	${FTE_ENGINE_CLIENT_DIR}/pr_csqc.c
	${FTE_ENGINE_CLIENT_DIR}/console.c
	${FTE_ENGINE_CLIENT_DIR}/image.c
	${FTE_ENGINE_CLIENT_DIR}/keys.c
	${FTE_ENGINE_CLIENT_DIR}/menu.c
	${FTE_ENGINE_CLIENT_DIR}/m_master.c
	${FTE_ENGINE_CLIENT_DIR}/m_multi.c
	${FTE_ENGINE_CLIENT_DIR}/m_items.c
	${FTE_ENGINE_CLIENT_DIR}/m_options.c
	${FTE_ENGINE_CLIENT_DIR}/m_single.c
	${FTE_ENGINE_CLIENT_DIR}/m_script.c
	${FTE_ENGINE_CLIENT_DIR}/m_native.c
	${FTE_ENGINE_CLIENT_DIR}/m_mp3.c
	${FTE_ENGINE_CLIENT_DIR}/roq_read.c
	${FTE_ENGINE_CLIENT_DIR}/clq2_cin.c
	${FTE_ENGINE_CLIENT_DIR}/r_part.c
	${FTE_ENGINE_CLIENT_DIR}/p_script.c
	${FTE_ENGINE_CLIENT_DIR}/p_null.c
	${FTE_ENGINE_CLIENT_DIR}/p_classic.c
	${FTE_ENGINE_CLIENT_DIR}/r_partset.c
	${FTE_ENGINE_CLIENT_DIR}/renderer.c
	${FTE_ENGINE_CLIENT_DIR}/renderque.c
	${FTE_ENGINE_CLIENT_DIR}/sbar.c
	${FTE_ENGINE_CLIENT_DIR}/skin.c
	${FTE_ENGINE_CLIENT_DIR}/snd_al.c
	${FTE_ENGINE_CLIENT_DIR}/snd_dma.c
	${FTE_ENGINE_CLIENT_DIR}/snd_mem.c
	${FTE_ENGINE_CLIENT_DIR}/snd_mix.c
	${FTE_ENGINE_CLIENT_DIR}/snd_mp3.c
	${FTE_ENGINE_CLIENT_DIR}/snd_ov.c
	${FTE_ENGINE_CLIENT_DIR}/valid.c
	${FTE_ENGINE_CLIENT_DIR}/vid_headless.c
	${FTE_ENGINE_CLIENT_DIR}/view.c
	${FTE_ENGINE_CLIENT_DIR}/wad.c
	${FTE_ENGINE_CLIENT_DIR}/pr_menu.c

	${FTE_ENGINE_HTTP_DIR}/ftpclient.c
)

set(FTE_ENGINE_CLIENT_ONLY_SOURCES
	$<$<BOOL:${FTE_ENGINE_USE_SDL}>:${FTE_ENGINE_CLIENT_DIR}/snd_sdl.c>
	$<$<BOOL:${FTE_ENGINE_USE_SDL}>:${FTE_ENGINE_CLIENT_DIR}/cd_sdl.c>
	$<$<BOOL:${FTE_ENGINE_USE_SDL}>:${FTE_ENGINE_CLIENT_DIR}/sys_sdl.c>
	$<$<BOOL:${FTE_ENGINE_USE_SDL}>:${FTE_ENGINE_CLIENT_DIR}/in_sdl.c>

	$<$<BOOL:${FTE_ENGINE_USE_SDL}>:${FTE_ENGINE_GL_DIR}/gl_vidsdl.c>
)

set(FTE_ENGINE_CLIENT_D3DGL_SOURCES
	${FTE_ENGINE_GL_DIR}/gl_font.c
	${FTE_ENGINE_GL_DIR}/gl_ngraph.c
	${FTE_ENGINE_GL_DIR}/gl_shader.c
	${FTE_ENGINE_GL_DIR}/gl_shadow.c
	${FTE_ENGINE_GL_DIR}/gl_rlight.c
	${FTE_ENGINE_GL_DIR}/gl_warp.c
	${FTE_ENGINE_GL_DIR}/ltface.c

	${FTE_ENGINE_CLIENT_DIR}/r_surf.c
	${FTE_ENGINE_CLIENT_DIR}/r_2d.c
)

if(FTE_ENGINE_BOTH)
	add_executable(fteqw
		${FTE_ENGINE_COMMON_SOURCES}
		${FTE_ENGINE_SERVER_SOURCES}
		${FTE_ENGINE_CLIENT_SOURCES}
		${FTE_ENGINE_PROGS_SOURCES}
		${FTE_ENGINE_CLIENT_ONLY_SOURCES}
		${FTE_ENGINE_CLIENT_D3DGL_SOURCES}
	)
	target_compile_options(fteqw PRIVATE ${FTE_COMMON_OPTIONS})
	target_compile_definitions(fteqw
		PRIVATE
			${FTE_COMMON_DEFINITIONS}
			$<$<BOOL:${FTE_ENGINE_USE_SDL}>:FTE_SDL>
			$<$<BOOL:$<TARGET_EXISTS:SDL3::SDL3>>:FTE_SDL3>
	)
	target_include_directories(fteqw
		PRIVATE
			${FTE_ENGINE_ROOT_DIR}
			${FTE_ENGINE_COMMON_DIR}
			${FTE_ENGINE_CLIENT_DIR}
			${FTE_ENGINE_QCLIB_DIR}
			${FTE_ENGINE_GL_DIR}
	)
	target_link_libraries(fteqw
		PRIVATE
			ZLIB::ZLIB
			$<TARGET_NAME_IF_EXISTS:Math::Math>
			$<TARGET_NAME_IF_EXISTS:Freetype::Freetype>
			$<TARGET_NAME_IF_EXISTS:SDL::SDL>
			$<TARGET_NAME_IF_EXISTS:SDL2::SDL2>
			$<TARGET_NAME_IF_EXISTS:SDL3::SDL3>
	)
	set_target_properties(fteqw
		PROPERTIES
			LIBRARY_OUTPUT_DIRECTORY ${FTE_ROOT_DIR}/game
			RUNTIME_OUTPUT_DIRECTORY ${FTE_ROOT_DIR}/game
			SUFFIX ${FTE_EXECUTABLE_SUFFIX}
	)
endif()

if(FTE_ENGINE_SERVER)
	add_executable(fteqw-sv
		${FTE_ENGINE_COMMON_SOURCES}
		${FTE_ENGINE_SERVER_SOURCES}
		${FTE_ENGINE_PROGS_SOURCES}
		${FTE_ENGINE_SERVER_ONLY_SOURCES}
	)
	target_compile_options(fteqw-sv PRIVATE ${FTE_COMMON_OPTIONS})
	target_compile_definitions(fteqw-sv
		PRIVATE
			SERVERONLY
			${FTE_COMMON_DEFINITIONS}
	)
	target_include_directories(fteqw-sv
		PRIVATE
			${FTE_ENGINE_ROOT_DIR}
			${FTE_ENGINE_COMMON_DIR}
			${FTE_ENGINE_CLIENT_DIR}
			${FTE_ENGINE_QCLIB_DIR}
			${FTE_ENGINE_GL_DIR}
	)
	target_link_libraries(fteqw-sv
		PRIVATE
			ZLIB::ZLIB
			$<TARGET_NAME_IF_EXISTS:Math::Math>
	)
	set_target_properties(fteqw-sv
		PROPERTIES
			LIBRARY_OUTPUT_DIRECTORY ${FTE_ROOT_DIR}/game
			RUNTIME_OUTPUT_DIRECTORY ${FTE_ROOT_DIR}/game
			SUFFIX ${FTE_EXECUTABLE_SUFFIX}
	)
endif()

if(FTE_ENGINE_CLIENT)
	add_executable(fteqw-cl
		${FTE_ENGINE_COMMON_SOURCES}
		${FTE_ENGINE_CLIENT_SOURCES}
		${FTE_ENGINE_PROGS_SOURCES}
		${FTE_ENGINE_CLIENT_ONLY_SOURCES}
		${FTE_ENGINE_CLIENT_D3DGL_SOURCES}
	)
	target_compile_options(fteqw-cl PRIVATE ${FTE_COMMON_OPTIONS})
	target_compile_definitions(fteqw-cl
		PRIVATE
			CLIENTONLY
			${FTE_COMMON_DEFINITIONS}
			$<$<BOOL:${FTE_ENGINE_USE_SDL}>:FTE_SDL>
			$<$<BOOL:$<TARGET_EXISTS:SDL3::SDL3>>:FTE_SDL3>
	)
	target_include_directories(fteqw-cl
		PRIVATE
			${FTE_ENGINE_ROOT_DIR}
			${FTE_ENGINE_COMMON_DIR}
			${FTE_ENGINE_CLIENT_DIR}
			${FTE_ENGINE_QCLIB_DIR}
			${FTE_ENGINE_GL_DIR}
	)
	target_link_libraries(fteqw-cl
		PRIVATE
			ZLIB::ZLIB
			$<TARGET_NAME_IF_EXISTS:Math::Math>
			$<TARGET_NAME_IF_EXISTS:Freetype::Freetype>
			$<TARGET_NAME_IF_EXISTS:SDL::SDL>
			$<TARGET_NAME_IF_EXISTS:SDL2::SDL2>
			$<TARGET_NAME_IF_EXISTS:SDL3::SDL3>
	)
	set_target_properties(fteqw-cl
		PROPERTIES
			LIBRARY_OUTPUT_DIRECTORY ${FTE_ROOT_DIR}/game
			RUNTIME_OUTPUT_DIRECTORY ${FTE_ROOT_DIR}/game
			SUFFIX ${FTE_EXECUTABLE_SUFFIX}
	)
endif()
