
if(NOT DEFINED CMAKE_SYSTEM_PROCESSOR)
	set(FTE_SYSTEM_PROCESSOR "unk")
else()
	string(TOLOWER ${CMAKE_SYSTEM_PROCESSOR} FTE_SYSTEM_PROCESSOR)
endif()

if(WIN32 OR MSVC OR CMAKE_SYSTEM_NAME STREQUAL "Windows")
	set(FTE_EXECUTABLE_SUFFIX "_${FTE_SYSTEM_PROCESSOR}.exe")
else()
	set(FTE_EXECUTABLE_SUFFIX ".${FTE_SYSTEM_PROCESSOR}")
endif()

set(FTE_SHARED_LIBRARY_SUFFIX "_${FTE_SYSTEM_PROCESSOR}${CMAKE_SHARED_LIBRARY_SUFFIX}")
