
include(FetchContent)

find_package(Math)
find_package(ZLIB REQUIRED)
if(FTE_ENGINE_BOTH OR FTE_ENGINE_CLIENT)
	if(FTE_ENGINE_SDL_VERSION_MAJOR STREQUAL "1")
		find_package(SDL REQUIRED)
		set(FTE_ENGINE_USE_SDL TRUE)
	elseif(FTE_ENGINE_SDL_VERSION_MAJOR STREQUAL "2")
		find_package(SDL2 REQUIRED)
		set(FTE_ENGINE_USE_SDL TRUE)
	elseif(FTE_ENGINE_SDL_VERSION_MAJOR STREQUAL "3")
		find_package(SDL3 REQUIRED)
		set(FTE_ENGINE_USE_SDL TRUE)
	else()
		set(FTE_ENGINE_USE_SDL FALSE)
	endif()
	if(FTE_ENGINE_RENDERER STREQUAL "gl")
		find_package(OpenGL REQUIRED)
	endif()
	find_package(Freetype)
	if(Freetype_FOUND)
		list(APPEND FTE_COMMON_DEFINITIONS AVAIL_FREETYPE)
	endif()
endif()
